app/views.py
import logging
import random
import json

from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for

from flask_login import login_required
from flask_login import current_user

from app.models import student
from app.models import user
from app.models import isu

blueprint = Blueprint('views', __name__)


@blueprint.route('/', methods=['GET'])
def home():
    return render_template('home.html')


@blueprint.route('/charts', methods=['GET', 'POST'])
def charts():

    if not current_user.is_authenticated():
        return redirect(url_for('views.home'), code=302)
    if request.method == 'POST':
        query_form = request.form
        college = query_form.get('college')
        major = query_form.get('major')
        student_type = query_form.get('student_type')
        year = query_form.get('year')

        try:
            year = int(year)
        except ValueError:
            pass


        students = []
        if major:
            student_query = student.Student.all().filter('major', major)
        elif college:
            student_query = student.Student.all().filter('college', college)
        else:
            student_query = student.Student.all()

        if year == 'all':
            students = student_query.fetch(limit=None)
        else:
            students = student_query.filter('year', year).fetch(limit=None)


        distribution = {}
        for s in students:
            key = getattr(s, student_type)

            if student_type == 'gpa':
                key = "%.1f" % (key,)
            elif student_type == 'gender':
                key = 'Male' if key else 'Female'
            elif student_type == 'oncampus':
                key = 'On Campus' if key else 'Off Campus'
            elif student_type == 'major':
                key = s.major

            distribution[s.year] = distribution.get(s.year, {})
            distribution[s.year][key] = distribution[s.year].get(key, 0) + 1

        return json.dumps({
            'distribution': distribution
        })


    return render_template('chart.html', colleges=isu.colleges.keys())


@blueprint.route('/isu/<college>/', methods=['GET'])
def iowa_state(college):
    return json.dumps(isu.colleges.get(college, []))


@blueprint.route('/auth/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('views.home'), code=302)

    if request.method == 'POST':
        login_form = request.form
        user.login(login_form.get('email'), login_form.get('password'))

        if current_user.is_authenticated():
            next_url = request.args.get('next',url_for('views.home'))
            return redirect(next_url, code=302)
        else:
            return render_template('login.html', failure=True, email=login_form.get('email'))

    return render_template('login.html', failure=False, email='')


@blueprint.route('/auth/logout', methods=['GET'])
def logout():
    user.logout()
    return redirect(url_for('views.home'), code=302)


@blueprint.route('/auth/register/<registration_id>', methods=['GET', 'POST'])
def register(registration_id):
    new_user = user.get_by_registration_id(registration_id)
    if not new_user or new_user.is_registered:
        return redirect(url_for('views.home'), code=302)

    if request.method == 'POST':
        registration_form = request.form
        new_password = registration_form.get('password', '')
        if len(new_password) < 6:
            return render_template('register.html', attempt={'failure':True}, user=new_user)

        user.register(registration_id, new_password)
        return redirect(url_for('views.home'), code=302)

    return render_template('register.html', attempt={}, user=new_user)


@blueprint.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    if not current_user.is_admin():
        return redirect(url_for('views.home'), code=302)

    if request.method == 'POST':
        admin_form = request.form
        user_role = admin_form.get('role', user.BASE_USER_ROLE)

        new_user = user.create_user(admin_form.get('email'), user_role)
        registration_url = url_for('views.register', registration_id=new_user.registration_id)

        return render_template('admin.html', new_user=new_user,
                                             registration_url=registration_url,
                                             users=user.get_users())

    return render_template('admin.html', new_user=None, users=user.get_users())

app/templates/admin.html
{% extends "base.html" %}

{% block title %}Admin{% endblock %}

{% block css %}
<style type="text/css">
  .row {
    padding-bottom: 10px;
  }
</style>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-12">
    <h1>Admin <br><small>Remember, with great power comes great responsibility.</small></h1>
  </div>
</div>

<div class="row">
  <form action="" class="form-horizontal" method="post">
    <div class="col-sm-8">
        <div class="input-group">
          <span class="input-group-addon">
            Create User
          </span>
          <input type="email" name="email" class="form-control" placeholder="email" required="" autofocus="">
          <span class="input-group-btn">
            <input class="btn btn-primary" id="add" type="submit" value="Add">
          </span>
        </div>
    </div>



    <label class="control-label col-sm-1" >Role</label>
    <div class="col-sm-3">
      <select name="role" class="form-control">
        <option value="admin">Admin</option>
        <option value="base-user-role" selected>Base User</option>
      </select>
    </div>

  </form>
</div>


{% if new_user %}
  <div class="row">
    <div class="col-sm-12">

      {% if new_user.is_registered %}
        <div class="alert alert-warning">
        {{ new_user.email }} has already been registered.
      {% else %}
        <div class="alert alert-success">
        {{ new_user.email }} was successfully created! You can register this account <a href="{{ registration_url }}">here</a>!
      {% endif %}

      </div>
    </div>
  </div>
{% endif %}

<div class="row">
  <div class="col-sm-12">
    <h1>User Directory</h1>
  </div>
</div>

<div class="row">
  <div class="form-group col-sm-12">
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Email</th>
        <th>Role</th>
        <th>Is Registered</th>
        <th>Registration ID</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <td>{{user.email}}</td>
          <td>{{user.role}}</td>
          <td>{{user.is_registered}}</td>
          <td>{{user.registration_id}}</td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
  </div>
</div>

{% endblock %}

{% block js %}{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="./favicon.ico">


    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <style type="text/css">
      body {
        padding-top: 50px;
      }
      .navbar-fixed-top, .navbar-fixed-bottom {
        z-index: 99;
      }
      .container {
        width: auto;
        max-width: 767px;
        padding: 0 15px;
      }
    </style>
    {% block css %}{% endblock %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="{%if request.path == url_for('views.home')%}active{%endif%}"><a href="{{ url_for('views.home') }}">Home</a></li>

            {% if current_user.is_authenticated() %}

              <li class="{%if request.path == url_for('views.charts')%}active{%endif%}"><a href="{{ url_for('views.charts') }}">Charts</a></li>
              {% if current_user.is_admin() %}
                <li class="{%if request.path == url_for('views.admin')%}active{%endif%}"><a href="{{ url_for('views.admin') }}">Admin</a></li>
              {% endif %}
            {% endif %}
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated() %}
              <li class="" ><a class="disable" href="#">{{ current_user.email }}</a></li>
              <li class=""><a href="{{ url_for('views.logout') }}">Logout</a></li>
            {% else %}
              <li class="{%if request.path == url_for('views.login')%}active{%endif%}"><a href="{{ url_for('views.login') }}">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script>
      $(document).ready(function() {
        $('a.disable').click(function(e) {
          e.preventDefault();
        });
      });
    </script>
    {% block js %}{% endblock %}
  </body>
</html>

app/templates/bootstrap_examples.html
{% extends "base.html" %}

{% block title %}Bootstrap Examples{% endblock %}

{% block css %}
<style type="text/css">
  img {
      width: 100px;
      height: 100px;
  }

  .input-group, .btn-group {
      margin-bottom: 10px;
  }
</style>
{% endblock %}

{% block content %}

  <h1> Hello World</h1>

  <div class="row">
      <div class="col-md-12">
          <h4>Test</h4>
          <p id="res"></p>
          <p> foo bar</p>
          <button type="button" class="btn btn-primary btn-lg">Primary button</button>
          <button type="button" class="btn btn-default btn-lg ">Button</button>

      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
          <div class="form-group has-success">
              <label class="control-label" for="inputSuccess">Input with success</label>
              <input type="text" class="form-control" id="inputSuccess">
          </div>


          <form class="form-horizontal" role="form">
              <div class="form-group">
                  <label class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-10">
                       <input type="email" class="form-control" id="inputEmail" placeholder="your@email.com">
                  </div>
              </div>
              <div class="form-group">
                  <label for="inputPassword" class="col-sm-2 control-label">Password</label>
                  <div class="col-sm-10">
                      <input type="password" class="form-control" id="inputPassword" placeholder="Password">
                  </div>
              </div>
          </form>
          <img src="http://upload.wikimedia.org/wikipedia/commons/2/2c/Chinchilla-Patchouli.jpg" alt="..." class="img-rounded">

          <table class="table table-striped">
              <thead>
                  <tr>
                      <th>#</th>
                      <th>First Name</th>
                      <th>Last Name</th>
                      <th>Username</th>
                  </tr>
              </thead>
              <tbody>
                  <tr>
                      <td>1</td>
                      <td>Mark</td>
                      <td>Otto</td>
                      <td>@mdo</td>
                  </tr>
                  <tr>
                      <td>2</td>
                      <td>Jacob</td>
                      <td>Thornton</td>
                      <td>@fat</td>
                  </tr>
                  <tr>
                      <td>3</td>
                      <td>Larry</td>
                      <td>the Bird</td>
                      <td>@twitter</td>
                  </tr>
              </tbody>
          </table>
          <p class="text-muted">For example, <code>&lt;section&gt;</code> should be wrapped as inline.</p>


          <div class="btn-group">
            <button type="button" class="btn btn-default">Left</button>
            <button type="button" class="btn btn-default">Middle</button>
            <button type="button" class="btn btn-default">Right</button>
          </div>


          <div class="input-group">
            <span class="input-group-addon">@</span>
            <input type="text" class="form-control" placeholder="Username">
          </div>

          <div class="input-group">
            <input type="text" class="form-control">
            <span class="input-group-addon">.00</span>
          </div>

          <div class="input-group">
            <span class="input-group-addon">$</span>
            <input type="text" class="form-control">
            <span class="input-group-addon">.00</span>
          </div>



          <div class="well well-sm">Look I'm a small well</div>


          <div class="panel panel-default">
            <div class="panel-body">
              Panel content
            </div>
            <div class="panel-footer">Panel footer</div>
          </div>



        <div class="media">
          <a class="pull-left" href="#">
            <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAACsklEQVR4Xu2Y24upYRTGl0PI0JSimHDjMIVETVMzpvzrziLSTIkiLpTcjJLzcfaziuz2Njufsb8La93o+3jX+65nHX55NZ+fnzu6YdOIAFIB0gIyA254BpIMQaGAUEAoIBQQCtywAoJBwaBgUDAoGLxhCMifIcGgYFAwKBgUDAoGb1iBizHYbDap3+/Tbrcjp9NJwWCQNBrNQdJflKF6vU5ms5lisdhv353S/Ro+T+11kQCNRoN6vR7p9Xr2v16vyev1kt/v52eIkkql+L3BYKBEIkFarfbberuGz+82VCzAZrOhdDrNGX17e6PVakXdbpesVis9PDzwnq1Wi9/BTCYTvb6+0mQyoff3d9LpdBSPx2k8HhOCNhqNFIlEKJvNnu3zuOLO7WbFAiyXSz7sdrvloOfzObdAIBDgM8xmM8rlcuTxeGg0GtF0OmWhcNhKpULD4ZBsNhuvw3eoGqxX6vPcwPe/VywAertarbIftADKHIYgQqEQlctlzm4ymaRSqUSLxeIgwLF4WHN/f09PT090ic//LgAynM/nuXRfXl44i8VikXs9HA6zOHd3d+R2u6ndbnOl+Hw+foZ1Oh1+D3t+fuYqutSnEhEUVwAyjhmA3oYA+2cI8Pj4SLVa7Y/zYACiIjAcM5nMoWrsdjtFo9GDDyU+/zVcT4mjWAAEgQpA1lwuF3+irx0OB1cAyhyGg6EdIBAyjeA+Pj5oMBiQxWLhykF1YABirVKfSrKPNYoFwGIMsEKhQCACDO2AXkaQx4bWgACgAAYiBNnTA0KA+5gje5qc61MVChwHiGEHQ0Z/yq7h829nu6gCfipYNf2IAHIjJDdCciMkN0JqTmG19xYKCAWEAkIBoYDak1jN/YUCQgGhgFBAKKDmFFZ7b6GAUEAoIBQQCqg9idXcXyhw6xT4AgyAjZ+ww1kxAAAAAElFTkSuQmCC">
          </a>
          <div class="media-body">
            <h4 class="media-heading">Media heading</h4>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>
        <div class="media">
          <a class="pull-left" href="#">
            <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAACsklEQVR4Xu2Y24upYRTGl0PI0JSimHDjMIVETVMzpvzrziLSTIkiLpTcjJLzcfaziuz2Njufsb8La93o+3jX+65nHX55NZ+fnzu6YdOIAFIB0gIyA254BpIMQaGAUEAoIBQQCtywAoJBwaBgUDAoGLxhCMifIcGgYFAwKBgUDAoGb1iBizHYbDap3+/Tbrcjp9NJwWCQNBrNQdJflKF6vU5ms5lisdhv353S/Ro+T+11kQCNRoN6vR7p9Xr2v16vyev1kt/v52eIkkql+L3BYKBEIkFarfbberuGz+82VCzAZrOhdDrNGX17e6PVakXdbpesVis9PDzwnq1Wi9/BTCYTvb6+0mQyoff3d9LpdBSPx2k8HhOCNhqNFIlEKJvNnu3zuOLO7WbFAiyXSz7sdrvloOfzObdAIBDgM8xmM8rlcuTxeGg0GtF0OmWhcNhKpULD4ZBsNhuvw3eoGqxX6vPcwPe/VywAertarbIftADKHIYgQqEQlctlzm4ymaRSqUSLxeIgwLF4WHN/f09PT090ic//LgAynM/nuXRfXl44i8VikXs9HA6zOHd3d+R2u6ndbnOl+Hw+foZ1Oh1+D3t+fuYqutSnEhEUVwAyjhmA3oYA+2cI8Pj4SLVa7Y/zYACiIjAcM5nMoWrsdjtFo9GDDyU+/zVcT4mjWAAEgQpA1lwuF3+irx0OB1cAyhyGg6EdIBAyjeA+Pj5oMBiQxWLhykF1YABirVKfSrKPNYoFwGIMsEKhQCACDO2AXkaQx4bWgACgAAYiBNnTA0KA+5gje5qc61MVChwHiGEHQ0Z/yq7h829nu6gCfipYNf2IAHIjJDdCciMkN0JqTmG19xYKCAWEAkIBoYDak1jN/YUCQgGhgFBAKKDmFFZ7b6GAUEAoIBQQCqg9idXcXyhw6xT4AgyAjZ+ww1kxAAAAAElFTkSuQmCC">
          </a>
          <div class="media-body">
            <h4 class="media-heading">Media heading</h4>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            <div class="media">
              <a class="pull-left" href="#">
                <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAACsklEQVR4Xu2Y24upYRTGl0PI0JSimHDjMIVETVMzpvzrziLSTIkiLpTcjJLzcfaziuz2Njufsb8La93o+3jX+65nHX55NZ+fnzu6YdOIAFIB0gIyA254BpIMQaGAUEAoIBQQCtywAoJBwaBgUDAoGLxhCMifIcGgYFAwKBgUDAoGb1iBizHYbDap3+/Tbrcjp9NJwWCQNBrNQdJflKF6vU5ms5lisdhv353S/Ro+T+11kQCNRoN6vR7p9Xr2v16vyev1kt/v52eIkkql+L3BYKBEIkFarfbberuGz+82VCzAZrOhdDrNGX17e6PVakXdbpesVis9PDzwnq1Wi9/BTCYTvb6+0mQyoff3d9LpdBSPx2k8HhOCNhqNFIlEKJvNnu3zuOLO7WbFAiyXSz7sdrvloOfzObdAIBDgM8xmM8rlcuTxeGg0GtF0OmWhcNhKpULD4ZBsNhuvw3eoGqxX6vPcwPe/VywAertarbIftADKHIYgQqEQlctlzm4ymaRSqUSLxeIgwLF4WHN/f09PT090ic//LgAynM/nuXRfXl44i8VikXs9HA6zOHd3d+R2u6ndbnOl+Hw+foZ1Oh1+D3t+fuYqutSnEhEUVwAyjhmA3oYA+2cI8Pj4SLVa7Y/zYACiIjAcM5nMoWrsdjtFo9GDDyU+/zVcT4mjWAAEgQpA1lwuF3+irx0OB1cAyhyGg6EdIBAyjeA+Pj5oMBiQxWLhykF1YABirVKfSrKPNYoFwGIMsEKhQCACDO2AXkaQx4bWgACgAAYiBNnTA0KA+5gje5qc61MVChwHiGEHQ0Z/yq7h829nu6gCfipYNf2IAHIjJDdCciMkN0JqTmG19xYKCAWEAkIBoYDak1jN/YUCQgGhgFBAKKDmFFZ7b6GAUEAoIBQQCqg9idXcXyhw6xT4AgyAjZ+ww1kxAAAAAElFTkSuQmCC">
              </a>
              <div class="media-body">
                <h4 class="media-heading">Nested media heading</h4>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>
          </div>

          <div class="alert alert-success">
            <a href="#" class="alert-link">...</a>
          </div>
        </div>

          <button id="tooltip" type="button" class="btn btn-default" data-original-title="" title="">Tooltip on left</button>
      </div>
  
</div>
{% endblock %}

{% block js %}
<script>
    $(document).ready(function() {
        $('#tooltip').tooltip({
            placement: 'top',
            title: 'Hello!'
        });
    });
</script>
{% endblock %}

app/templates/chart.html
{% extends "base.html" %}

{% block title %}Chart JS Demo{% endblock %}

{% block css %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/nprogress/0.1.2/nprogress.css">
<style type="text/css">
  canvas {
    padding-top: 25px;
  }
  #legend > span {
    padding-right: 25px;
  }
</style>
{% endblock %}


{% block content %}


<div class="row">
  <div class="col-sm-12">
    <h1>Chart <br><small>Show data by...</small></h1>
  </div>
</div>


<div class="row">
  <div class="form-group col-sm-4">
    <label for="student_year">Year</label>
    <select name="student_year" class="form-control" id="student_year">
      <option value="all" selected>all recorded years</option>
      <option value="2012">2012</option>
      <option value="2013" >2013</option>
      <option value="2014">2014</option>
    </select>
  </div>
</div>

<div class="row">

  <div class="form-group col-sm-4">
    <label for="student_type">Student Property</label>
    <select name="student_type" class="form-control" id="student_type">
      <option value="gpa">GPA</option>
      <option value="age">Age</option>
      <option value="gender">Gender</option>
      <option value="oncampus">Living On/Off Campus</option>
      <option value="major">Major Distribution</option>
    </select>
  </div>

  <div class="form-group col-sm-4">
    <label for="college">College of</label>
    <select name="college" class="form-control" id="college">
      <option value="">-</option>
      {% for college in colleges %}
      <option value="{{college}}">{{college}}</option>
      {% endfor %}
    </select>
  </div>

  <div class="form-group col-sm-4">
    <label for="major">Major</label>
    <select name="major" class="form-control" id="major" disabled>
      <option value="">-</option>
    </select>
  </div>

</div>
<div class="row">
  <div class="col-sm-12">
    <input class="btn btn-primary btn-lg pull-right" id="submit" type="submit" value="Update">
  </div>
</div>

<div class="row">
  <div id="legend" class="col-sm-12">

  </div>
</div>

<canvas id="myChart" width="700" height="400"></canvas>

{% endblock %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.1.2/nprogress.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.min.js"></script>
<script>
  Array.min = function( array ){
      return Math.min.apply( Math, array );
  };
  Array.max = function( array ){
      return Math.max.apply( Math, array );
  };
  var isInArray = function(array, search) {
      return (array.indexOf(search) >= 0) ? true : false; 
  };

  $(document).ready(function() {
      NProgress.configure({ trickleRate: 0.10, trickleSpeed: 350 });
    $('#submit').click(function(e) {
      NProgress.start();
      var data = {
        major: $('#major').val(),
        college: $('#college').val(),
        student_type: $('#student_type').val(),
        year: $('#student_year').val()
      };
      $.ajax({
        type: 'POST',
        url: '{{ url_for("views.charts") }}',
        dataType: 'json',
        data: data,
        complete: function(data){
          NProgress.done();
          var distribution = data.responseJSON.distribution;

          var graph_data = {
            labels : [],
            datasets : [
              {
                fillColor : "rgba(151,187,205,0.2)",
                strokeColor : "rgba(151,187,205,1)",
                data : []
              },
              {
                fillColor : "rgba(220,220,220,0.2)",
                strokeColor : "rgba(220,220,220,1)",
                data : []
              },
              {
                fillColor : "rgba(151,205,187,0.2)",
                strokeColor : "rgba(151,205,187,1)",
                data : []
              }
            ]
          };

          $('#legend').html('');
          var currentColorIndex = 0;
          for(var year in distribution) {
            if (distribution.hasOwnProperty(year)) {

              for(var distribution_group in distribution[year]) {
                if(distribution[year].hasOwnProperty(distribution_group)){
                  if (! isInArray(graph_data.labels, distribution_group))
                    graph_data.labels.push(distribution_group);
                  graph_data.datasets[currentColorIndex].data.push(distribution[year][distribution_group]);
                }
              }

              $('#legend').append([
                '<span style="color:',graph_data.datasets[currentColorIndex].strokeColor,';">',
                year,
                '</span>'].join('')
              );
              currentColorIndex = currentColorIndex + 1;
              
            }
          }

          if(currentColorIndex < 2)
              graph_data.datasets.splice(currentColorIndex, 3 - currentColorIndex);

          graph_data.labels.sort(function(a, b) {
            return a - b; // I'm cheating some data here...
          });

          var ctx = $("#myChart").get(0).getContext("2d");
          var steps = [];

          for (var i = 0; i < currentColorIndex; i++)
          {
            steps = steps.concat(graph_data.datasets[i].data);
          }

          var options = {
            scaleOverride : true,
            scaleSteps : Array.max(steps) - Array.min(steps)+2,
            scaleStepWidth : 1,
            scaleStartValue : Array.min(steps)-2
          };

          var studentType = $('#student_type').val();
          if (studentType === 'gender' || studentType === 'oncampus')
            new Chart(ctx).Bar(graph_data,options);
          else
            new Chart(ctx).Line(graph_data,options);
        }
      });
    });


    $("#college" ).change(function(e) {
      var element = $(this);
      $.ajax({
        type: 'GET',
        url: '/isu/' + element.val(),
        dataType: 'json',
        complete: function(data){
          var majors = data.responseJSON;
          var newOptions = '<option value="">-</option>';
          for (var i=0; i<majors.length; i++) {
            var major = majors[i];
            newOptions += '<option value="' + major + '">' + major + '</option>';
          }
          $('#major').removeAttr('disabled')
                     .html(newOptions);
        }
      });

    });


  });
</script>

{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block css %}
<style type="text/css">

  .jumbotron {
    text-align: center;
    margin-top: 30px;
    background-color: rgba(238, 238, 238, 0.90);
  }

  body {
      background: url(http://farm2.staticflickr.com/1378/5118138509_db47a65c54_o.jpg) no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
  }

</style>
{% endblock %}
{% block content %}
<div class="jumbotron">
  <h1>Uptown Saturday Night</h1>
  <p class="lead">Welcome to our project demo!</p>
</div>
{% endblock %}

{% block js %}{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block css %}
<style>
.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
}

.form-signin .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}

</style>
{% endblock %}

{% block content %}

<h2 class="">Welcome, {{ user.email }} please create a password for your account.</h2>

  {% if attempt.get('failure', False) %}
<form class="form-signin has-error" action="" method="post">
    <div class="alert alert-danger">Password must be at least 6 characters!</div>
  {% else %}

<form class="form-signin" action="" method="post">
  {% endif %}


  <input type="password" name="password" class="form-control" placeholder="password" required="" autofocus="">

  <input class="btn btn-primary btn-lg pull-right" id="submit" type="submit" value="Register">
</form>

{% endblock %}

{% block js %}{% endblock %}